openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: API documentation for the e-commerce application
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/carts/{cid}:
    get:
      summary: Retrieve a cart by ID
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: The cart ID.
      responses:
        '200':
          description: A cart.
        '500':
          description: Internal server error
    delete:
      summary: Delete all products from a cart
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: The cart ID.
      responses:
        '204':
          description: No content.
        '500':
          description: Internal server error
    put:
      summary: Update the products in a cart
      tags:
        - Cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
          description: The cart ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  productId:
                    type: string
                    description: The product ID
                  quantity:
                    type: integer
                    description: The quantity of the product
                required:
                  - productId
                  - quantity
      responses:
        '200':
          description: Successfully updated the cart
        '400':
          description: Bad request
        '404':
          description: Cart not found
        '500':
          description: Internal server error
components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: number
