openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: API documentation for the e-commerce application
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/products:
    get:
      summary: Retrieve all products
      tags:
        - Product
      responses:
        '200':
          description: A list of products.
        '500':
          description: Internal server error
  /api/products/{pid}:
    get:
      summary: Retrieve a product by ID
      tags:
        - Product
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: The product ID.
      responses:
        '200':
          description: A product.
        '404':
          description: Product not found.
    put:
      summary: Update a product by ID
      tags:
        - Product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: The product ID.
      requestBody:
        description: Product object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: The updated product.
        '404':
          description: Product not found.
        '500':
          description: Internal server error.
    delete:
      summary: Delete a product by ID
      tags:
        - Product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: The product ID.
      responses:
        '204':
          description: No content.
        '404':
          description: Product not found.
components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        discountPercentage:
          type: number
        rating:
          type: number
        status:
          type: boolean
        stock:
          type: number
        brand:
          type: string
        category:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT