openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: API documentation for the e-commerce application
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/sessions/login:
      post:
        summary: User login
        tags:
          - Auth
        security:
        - bearerAuth: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: user@example.com
                  password:
                    type: string
                    example: yourpassword
        responses:
          '200':
            description: Login successful, returns a JWT token
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    token:
                      type: string
                      example: token
          '401':
            description: Unauthorized
          '500':
            description: Internal server error